
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-02
owner: ucsb-cs156-f25
repo_name: team02-f25-02
pull_requests: [{"author":{"id":"MDQ6VXNlcjcyMTY4MzQ5","is_bot":false,"login":"AgamMakkar21","name":""},"headRefName":"am-articles-e2e-tests","number":127,"title":"Am articles e2e tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-02/pull/127"},{"author":{"id":"U_kgDOBnWR7A","is_bot":false,"login":"gavincao2023","name":"Gavin Cao"},"headRefName":"gavincao2023-MenuItemReview-team03","number":125,"title":"Add integration and E2E tests for MenuItemReview","url":"https://github.com/ucsb-cs156-f25/team02-f25-02/pull/125"},{"author":{"id":"U_kgDODf0g7A","is_bot":false,"login":"m4ttblanke","name":"Matt Blanke"},"headRefName":"mb-UCSBOrganization-e2e-test","number":123,"title":"mb - UCSBOrganization End-to-End Test","url":"https://github.com/ucsb-cs156-f25/team02-f25-02/pull/123"},{"author":{"id":"U_kgDODf0g7A","is_bot":false,"login":"m4ttblanke","name":"Matt Blanke"},"headRefName":"mb-UCSBOrganization-integration-test","number":122,"title":"mb - UCSBOrganization Integration Test","url":"https://github.com/ucsb-cs156-f25/team02-f25-02/pull/122"},{"author":{"id":"MDQ6VXNlcjcyMTY4MzQ5","is_bot":false,"login":"AgamMakkar21","name":""},"headRefName":"am-articles-integration-tests","number":117,"title":"Am articles integration tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-02/pull/117"}]
