
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team02-f25-02
owner: ucsb-cs156-f25
repo_name: team02-f25-02
pull_requests: [{"author":{"id":"U_kgDOBYAf9w","is_bot":false,"login":"pewpewpew0","name":""},"headRefName":"ml-helpRequest-e2e-tests","number":144,"title":"ml - help request e2e tests","url":"https://github.com/ucsb-cs156-f25/team02-f25-02/pull/144"}]
